<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Artist__gB1lxCfXeR8_Wze5Cx9</name>
   <tag></tag>
   <elementGuidId>f995277d-82a3-4efd-94da-c04c5925c245</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='searchPage']/div/div/section/div[2]/div/div/div/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._gB1lxCfXeR8_Wze5Cx9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_gB1lxCfXeR8_Wze5Cx9</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>herocard-click-handler</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchPage&quot;)/div[@class=&quot;iKwGKEfAfW7Rkx2_Ba4E khkfPsJuVBQyL_5cLT7y&quot;]/div[@class=&quot;iKwGKEfAfW7Rkx2_Ba4E nGARy02O1AklvHT7OBLA&quot;]/section[@class=&quot;iGyMsGo7FgYQQThBj2y9 QyANtc_r7ff_tqrf5Bvc&quot;]/div[@class=&quot;iKwGKEfAfW7Rkx2_Ba4E Z4InHgCs2uhk0MU93y_a&quot;]/div[@class=&quot;eITFAR9yPwhjL_2gxB09&quot;]/div[@class=&quot;HkbHLcqgUfXruL5xVi28&quot;]/div[@class=&quot;kVHQenQh3yKEk2n7Ere4&quot;]/div[@class=&quot;_gB1lxCfXeR8_Wze5Cx9&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchPage']/div/div/section/div[2]/div/div/div/div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/div/div/div/div[4]</value>
   </webElementXpaths>
</WebElementEntity>
